on:
  issue_comment:
    types: [created]

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/re-trigger') }}
    runs-on: ubuntu-latest
    steps:
      - name: Add temporary re-trigger label
        uses: actions-ecosystem/action-add-labels@18f1af5e3544586314bbe15c0273249c770b2daf # v1
        with:
          labels: pipeline/trigger

      - name: Comment a PR
        uses: actions/github-script@10b53a9ec6c222bb4ce97aa6bd2b5f739696b536 # v4
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'The certification pipeline will be triggered soon.'
            })

      - name: Remove a temporary label
        uses: actions-ecosystem/action-remove-labels@2ce5d41b4b6aa8503e285553f75ed56e0a40bae0 # v1
        with:
          labels: pipeline/trigger
